name: NightMadness
version: '${project.version}'
main: me.stephenminer.nightmadness.NightMadness
api-version: '1.20'

commands:
  spawnmob:
    permission: night-madness.commands.spawn
  nightmadness-reload:
    permission: night-madness.commands.reload
  spawnpatrol:
    permission: night-madness.commands.spawn
